[project]
enable_telemetry = true
user_env = []
session_timeout = 3600
cache = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
auto_tag_thread = true

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
min_decibels = -45
initial_silence_timeout = 3000
silence_timeout = 1500
max_duration = 15000
chunk_duration = 1000
sample_rate = 44100

edit_message = true

[UI]
name = "Assistant"
default_collapse_content = true
cot = "full"
custom_css = '/public/custom.css'



[UI.theme]
default = "dark"

# Override default MUI light theme. (Check theme.ts)
[UI.theme.light]
background = "#F0F0F0"
paper = "#FFFFFF"

[UI.theme.light.primary]
main = "#005A9C"  # Blue color similar to the logo
dark = "#004075"  # Darker shade of blue
light = "#E6F2FB"  # Light blue tone

[UI.theme.light.text]
primary = "#212121"
secondary = "#616161"

# Override default MUI dark theme. (Check theme.ts)
[UI.theme.dark]
background = "#1C1C1C"
paper = "#2C2C2C"

[UI.theme.dark.primary]
main = "#005A9C"  # Blue color similar to the logo
dark = "#004075"  # Darker shade of blue
light = "#E6F2FB"  # Light blue tone

[UI.theme.dark.text]
primary = "#EEEEEE"
secondary = "#BDBDBD"

[meta]
generated_by = "1.1.402"
